🔧 chore(latest): latest

diff --git a/.config/taskfiles/docker/Taskfile-update.yml b/.config/taskfiles/docker/Taskfile-update.yml
--- a/.config/taskfiles/docker/Taskfile-update.yml
+++ b/.config/taskfiles/docker/Taskfile-update.yml
@@ -95,3 +95,43 @@ tasks:
       - sed -i "s^.*org.opencontainers.image.vendor.\*^LABEL org.opencontainers.image.vendor=\"{{.ORGANIZATION}}\"^g" Dockerfile
 # yamllint enable rule:line-length
 # eslint-enable max-len
+
+  retag:
+    vars:
+      MAJOR_VERSION:
+        sh: echo '{{.NEW_VERSION}}' | sed 's/\..*\..*$//'
+    log:
+      error: Error retagging Docker container
+      start: Retagging Docker container
+      success: Successfully retagged Docker container
+    cmds:
+      - docker tag {{.DOCKER_IMAGE}}:latest {{.DOCKER_IMAGE}}:{{.NEW_VERSION}}
+      - docker tag {{.DOCKER_IMAGE}}:latest {{.DOCKER_IMAGE}}:{{.MAJOR_VERSION}}-latest
+      - docker rmi {{.DOCKER_IMAGE}}:{{.PREV_VERSION}}
+      - docker rmi {{.DOCKER_IMAGE}}:{{.MAJOR_VERSION}}-latest
+    status:
+      - '[ "{{.PREV_VERSION}}" == "{{.NEW_VERSION}}" ]'
+
+  version:
+    vars:
+      VERSION_COMMAND:
+        sh: jq -r '.blueprint.versionCommand' package.json
+    log:
+      error: Error acquiring software version
+      start: Acquiring software version
+      success: Finished software version acquisition sequence
+    cmds:
+      - |
+        VERSION="$({{.VERSION_COMMAND}})" | EXIT_CODE=$?
+        if [ -n "$EXIT_CODE" ]; then
+          .config/log warn 'Failed to run version command (`{{.VERSION_COMMAND}}`) - will retry after images are finished building'
+        else
+          CURR_VERSION="$(jq -r '.version' package.json)"
+          TMP="$(mktemp)"
+          jq --arg version "$VERSION" '.version = $version' package.json > "$TMP"
+          mv "$TMP" package.json
+          if [ "$CURR_VERSION" != "$VERSION" ]; then
+            .config/log info 'Updating documentation with new software version'
+            task common:update:update
+          fi
+        fi
diff --git a/.config/taskfiles/fix/Taskfile.yml b/.config/taskfiles/fix/Taskfile.yml
--- a/.config/taskfiles/fix/Taskfile.yml
+++ b/.config/taskfiles/fix/Taskfile.yml
@@ -65,12 +65,12 @@ tasks:
       - :install:modules:local
       - :install:npm:eslint
     desc: Auto-fix only modified files with ESLint
-    env:
-      ESLINT_STAGED_ONLY: on
     log:
       error: Failed to auto-fix modified files with ESLint
       start: Auto-fixing modified files with ESLint
       success: Successfully auto-fixed modified files with ESLint
+    env:
+      ESLINT_STAGED_ONLY: 'on'
     cmds:
       - >
         {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
@@ -207,6 +207,24 @@ tasks:
           done < <(find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f)
         {{end}}
 
+
+  spelling:markdown:
+    deps:
+      - :install:go:misspell
+    desc: Auto-fix spelling errors in markdown files using `misspell`
+    log:
+      error: Encountered error while attempting to auto-correct spelling mistakes with `misspell`
+      start: Auto-fixing using the `misspell` spell-check engine
+      success: Successfully auto-fixed files using `misspell`
+    cmds:
+      - >
+        {{if .CLI_ARGS}}
+        misspell -w {{.CLI_ARGS}}
+        {{else}}
+        find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.md' \)
+        -print0 | xargs -0 -r -n1 misspell -w
+        {{end}}
+
   packer:
     deps:
       - :install:software:packer
@@ -289,12 +307,13 @@ tasks:
     log:
       start: Running Prettier on {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}project{{end}}
     cmds:
-      - |
-        {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
-        if [ -n "$EXIT_CODE" ]; then
-          .config/log warn 'Failed to run `{{.NPX_HANDLE}}prettier` - falling back to `prettier`'
-          prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
-        fi
+      - cmd: |
+          {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
+          if [ -n "$EXIT_CODE" ]; then
+            .config/log warn 'Failed to run `{{.NPX_HANDLE}}prettier` - falling back to `prettier`'
+            prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+          fi
+        ignore_error: true
 
   python:
     deps:
@@ -371,23 +390,6 @@ tasks:
         {{else}}
           find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.sh' -o -name '*.sh.j2' \) \
             -print0 | xargs -0 {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}} -f diff | git apply
-        {{end}}
-
-  spelling:markdown:
-    deps:
-      - :install:go:misspell
-    desc: Auto-fix spelling errors in markdown files using `misspell`
-    log:
-      error: Encountered error while attempting to auto-correct spelling mistakes with `misspell`
-      start: Auto-fixing using the `misspell` spell-check engine
-      success: Successfully auto-fixed files using `misspell`
-    cmds:
-      - >
-        {{if .CLI_ARGS}}
-        misspell -w {{.CLI_ARGS}}
-        {{else}}
-        find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.md' \)
-        -print0 | xargs -0 -r -n1 misspell -w
         {{end}}
 
   toml:
